### ISSUE TITLE
Integration with `keepInventory`

### ISSUE THREAD

**Issue by srnyx** [srnyx/limited-lives#10]
**Split from #7**

If the server has the gamerule set to true, players should only drop items when they lose their last life, so the items in their inventory can be picked by other players.
This should probably be a toggle in the config

**Comment by NoodleDood1e** [comment]
I found a bug
When a player loses their last life, instead of dropping all their items, the items just get deleted, and are lost for good
The integration works well with other life amounts. As in, the players do not lose items on death

**Comment by srnyx** [comment]
> I found a bug When a player loses their last life, instead of dropping all their items, the items just get deleted, and are lost for good The integration works well with other life amounts. As in, the players do not lose items on death

Hi, sorry it took so long for me to get back to this!
Due to some issues with the gamerule, I had to draft a new system for the integration, do you think this would work for you?
```yml
# THE keepInventory GAMERULE MUST BE SET TO false FOR THIS TO WORK!
# If it isn't, some players' inventories may be permanently lost!
keep-inventory:
  # This will toggle this entire feature on or off
  enabled: false
  # The actions that will be taken when a player dies for the first, last, or X time
  # keep: Keep the player's inventory, as if keepInventory was true
  # drop: Drop the player's inventory on the ground, as if keepInventory was false
  # destroy: Destroy all items in the player's inventory
  actions:
    default: keep # The default action if the death isn't specified below
    first: destroy # EXAMPLE: This would be the player's first death
    5: drop # EXAMPLE: This would be the player's 5th death
    last: drop # EXAMPLE: This would be the player's last death
```
